sBitx version 4.0 Enhanced (#84)
Version 4.0 introduces a wealth of features and enhancements, including improved FT8 mode performance, a more responsive CW experience, a new TX Monitor function, and extensive UI improvements, among many other updates. Please see the release notes at https://raw.githubusercontent.com/drexjj/sbitx/refs/heads/main/release_notes.txt for more information.

---------

Co-authored-by: Alan Huseby <awh@brainless.us>
Co-authored-by: sigmazgfx <sigmazgfx@gmail.com>
Co-authored-by: Lars Lund Hansen <larslund.hansen@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,4 @@
+
 #!/bin/sh -e
 # Note: the '-e' flag will make the script stop immediately upon error with 
 # the error reflected in the environment.  This lets one issue commands like
@@ -8,16 +9,35 @@ O=$2
 OPT=0
 FLAGS="-g"
 [ -z "$F" ] && {
-   echo "usage:   $0 program [o]"
+   echo "usage:   $0 program [o|g|u]"
    echo "example: $0 sbitx"
    echo "-optional 'o' argument enables compiler optimizations"
+   echo "-optional 'g' argument enables profile generation"
+   echo "-optional 'u' argument enables usage of profile to guide optimizations"
    exit 1
 }
 if [ ! -z "$O" ] && [ "$O" = "o" ] ; then
 	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
 	echo "!! Building optimized binary, most warnings can be safely ignored !!"
 	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-	FLAGS="-O3 -flto=auto"
+	FLAGS="-march=native -O3 -flto=auto"
+	OPT=1
+	rm -f *.gcda
+fi
+if [ ! -z "$O" ] && [ "$O" = "g" ] ; then
+	rm -f *.gcda
+	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+	echo "!! Building profile generating binary                             !!"
+	echo "!! Run the application in your normal use case, then rerun with   !!"
+	echo "!! the u option to generate a profile guided optimized build      !!"
+	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+	FLAGS="-march=native -O3 -flto=auto -fprofile-generate"
+fi
+if [ ! -z "$O" ] && [ "$O" = "u" ] ; then
+	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+	echo "!! Building profile guided binary                                 !!"
+	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+	FLAGS="-march=native -O3 -flto=auto -fprofile-use"
 	OPT=1
 fi
 WORKING_DIRECTORY=`pwd`
@@ -45,7 +65,7 @@ fi
 gcc $FLAGS -o $F \
 	 src/vfo.c src/si570.c src/sbitx_sound.c src/fft_filter.c src/sbitx_gtk.c src/sbitx_utils.c \
     src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
-		src/modem_cw.c src/settings_ui.c src/ntputil.c \
+		src/modem_cw.c src/settings_ui.c src/hist_disp.c src/ntputil.c \
 		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/para_eq.c src/webserver.c src/eq_ui.c src/$F.c  \
 		src/ft8_lib/libft8.a  \
 	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt \
@@ -57,11 +77,46 @@ if [ $OPT -eq 1 ]; then
 	strip $F
 fi
 
+# Open the user_settings.ini file, search for #60m=, and add it if missing
+if [ -f "$HOME/sbitx/data/user_settings.ini" ]; then
+    echo "Checking user_settings.ini for 60 meters"
+    if ! grep -q "^#60m=" "$HOME/sbitx/data/user_settings.ini"; then
+        echo "Adding 60 meter band to user_settings.ini"
+        sed -i '/#40m=/a\#60m=' "$HOME/sbitx/data/user_settings.ini"
+    else
+        echo "60 meter band already exists in user_settings.ini"
+    fi
+else
+    echo "user_settings.ini not found"
+fi
 
-echo "Brought to you by the sBitx 64 bit project team - W9JES, W2JON, KF7YDU, and N1QM" 
+# Update hw_settings.ini to add 60m band configuration
+if [ -f "$HOME/sbitx/data/hw_settings.ini" ]; then
+    echo "Checking hw_settings.ini for 60m band"
+    if grep -q "f_start=5250000" "$HOME/sbitx/data/hw_settings.ini"; then
+        echo "60m band already exists in hw_settings.ini"
+    else
+        echo "Adding 60m band to hw_settings.ini"
+        awk '{
+          print $0
+        } /f_start=3500000/ {
+          found=1
+        } found && /scale=/ {
+          print ""
+          print "[tx_band]\nf_start=5250000\nf_stop=5450000\nscale=0.0033"
+          found=0
+        }' $HOME/sbitx/data/hw_settings.ini > temp.ini && mv temp.ini $HOME/sbitx/data/hw_settings.ini
+    fi
+else
+    echo "hw_settings.ini not found"
+fi
+
+echo "Brought to you by the sBitx 64 bit project team - W9JES, W2JON, N1QM, OZ7BX, and KF7YDU" 
 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
 # This addition is used to provide the application the capability to adjust the local system time -W2JON
 # It should probably always run last at it'll fail if the file system doesn't support it - N1QM
 if [ "$F" = "sbitx" ] && [ -x $F ]; then 
-	sudo setcap CAP_SYS_TIME+ep $F
+	# || : is a little hack to allow the script to continue if an error occurs - n1qm
+	sudo setcap CAP_SYS_TIME+ep $F || :
 fi
+echo Build completed at $(date)
