reset to 5.2

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,6 @@
+
 #!/bin/sh -e
-# Note: the '-e' flag will make the script stop immediately upon error with
+# Note: the '-e' flag will make the script stop immediately upon error with 
 # the error reflected in the environment.  This lets one issue commands like
 # "./build sbitx && ./sbitx" to build then run if it built correctly, and not
 # run if the build failed.
@@ -46,25 +47,12 @@ mkdir -p "./audio"
 mkdir -p "./data"
 mkdir -p "./web"
 
-git submodule update --init
-
 if test -f "data/sbitx.db"; then
-	HAS_TX_POWER=`sqlite3 data/sbitx.db "SELECT COUNT(*) AS CNTREC FROM pragma_table_info('logbook') WHERE name='tx_power'"`
-	HAS_FTX_RULES=`sqlite3 data/sbitx.db "SELECT COUNT(*) AS CNTREC FROM pragma_table_info('ftx_rules') WHERE name='regex'"`
-	if [ "$HAS_FTX_RULES" -eq 0 ]; then
-		sqlite3 data/sbitx.db < data/add_ftx_rules.sql
-	fi
-	if [ "$HAS_TX_POWER" -eq 0 ]; then
-		echo "new columns will be added to the database"
-		sqlite3 data/sbitx.db < data/add_columns.sql
-	else
-		echo "database is intact"
-	fi
+	echo "database is intact"
 else
 	echo "database doesn't exist, it will be created"
 	cd data
 	sqlite3 sbitx.db < create_db.sql
-	sqlite3 sbitx.db < add_ftx_rules.sql
 	cd ..
 fi
 
@@ -74,9 +62,18 @@ else
   VERSION=`grep VER src/sdr_ui.h | awk 'FNR==1{print $4}' | sed -e 's/"//g'`
   echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
 fi
-make clean
-make sbitx
+# Define Mongoose SSL flags - ensure OpenSSL is properly enabled
+MONGOOSE_FLAGS="-DMG_ENABLE_OPENSSL=1 -DMG_ENABLE_MBEDTLS=0 -DMG_ENABLE_LINES=1 -DMG_TLS=MG_TLS_OPENSSL -DMG_ENABLE_SSI=0 -DMG_ENABLE_IPV6=0"
 
+gcc $FLAGS $MONGOOSE_FLAGS -o $F \
+	 src/vfo.c src/si570.c src/sbitx_sound.c src/fft_filter.c src/sbitx_gtk.c src/sbitx_utils.c \
+    src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
+		src/modem_cw.c src/settings_ui.c src/hist_disp.c src/ntputil.c \
+		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/para_eq.c src/webserver.c src/eq_ui.c src/$F.c  \
+		src/ft8_lib/libft8.a  \
+	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt -lssl -lcrypto \
+	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
+ 
 if [ $OPT -eq 1 ]; then
 	#Remove debugging stuff for a smaller binary
 	echo Stripping $F
@@ -117,12 +114,12 @@ else
     echo "hw_settings.ini not found"
 fi
 
-# Set permissions to (755) so all web scripts from x Launcher work properly
-echo "Setting permissions to 755 on web script files"
-for file in "$HOME/sbitx/web/scripts"/*.sh; do
-    [ -f "$file" ] && chmod 755 "$file"
-done
-
-echo "Brought to you by the volunteer development Team for sBitx"
+echo "Brought to you by the sBitx 64 bit project team" 
 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
-echo $F Build version $VERSION completed at $(date)
+# This addition is used to provide the application the capability to adjust the local system time -W2JON
+# It should probably always run last at it'll fail if the file system doesn't support it - N1QM
+if [ "$F" = "sbitx" ] && [ -x $F ]; then 
+	# || : is a little hack to allow the script to continue if an error occurs - n1qm
+	sudo setcap CAP_SYS_TIME+ep $F || :
+fi
+echo Build completed at $(date)
